---
title: "tmt_default"
author: "A.G."
date: "`r Sys.Date()`"
---
```{r echo=FALSE, warning=FALSE}

cells_comparison_results <- cells_comparison$ComparisonResult %>% 
  clean_names()

cells_comparison_results <- cells_comparison_results %>% 
  janitor::clean_names()

cells_comparison_results <- left_join(
  cells_comparison_results,
  select(evidence, "Proteins", "Gene.names"),
  by = c("protein" = "Proteins")
) %>% distinct() %>% 
  clean_names()

cells_comparison_results <- cells_comparison_results %>% 
  dplyr::mutate(
    color = case_when(
      pvalue < 0.01 & log2fc > 0 ~ "#488f31",
      pvalue < 0.01 & log2fc < 0 ~ "#de425b",
      pvalue < 0.05 & log2fc > 0 ~ "#a8c162",
      pvalue < 0.05 & log2fc < 0 ~ "#f9a160",
      TRUE ~ "grey"
    ),
    label = case_when(
      pvalue < 0.01 ~ gene_names
    )
  )

cells_comparison_results <- cells_comparison_results %>% 
  dplyr::mutate(
    minus_log10_adj_pvalue = -log10(adj_pvalue)
  )

#paste(Gene.names, Protein, sep = "\n")

cells_comparison_results %>% 
  ggplot(aes(
    x = log2FC,
    y = -log10(pvalue),
    color = color,
    label = label
  )) +
  geom_point() +
  scale_colour_identity() +
  geom_text_repel(size = 3, force_pull = 5)
```

```{r echo=FALSE, warning=FALSE}

breaksRange <- function(data) {
  breaks <- c(1, 0.05, 0.01)
  i <- length(breaks)
  while (breaks[i] > min(data$pvalue)) {
    breaks <- append(breaks, breaks[i] / 10)
    i <- i + 1
  }
  return(breaks)
}

breaks <- breaksRange(cells_comparison_results)

cells_comparison_results %>% 
  ggplot(aes(
    x = log2fc,
    y = pvalue,
    label = label,
    color = adj_pvalue
  )) +
  geom_point() +
  scale_y_continuous(
    labels = label_math(expr = .x),
    trans = custom_reverse_log_trans(10),
    breaks = breaks,
    limits = c(1, 1e-10)
  ) +
  ggthemes::theme_base(
#    base_size = 12, 
    base_family = "googlesans_regular"
  ) +
  theme(plot.background = element_rect(color = NA)) +
  xlab(bquote(Delta*S)) +
  ylab(bquote(italic(p)*-value)) +
  geom_text_repel(
    family = "googlesans_regular",
    box.padding = 0.25,
    max.overlaps = 15
  ) +
  scale_color_gradientn(
    colors = c("black", "red", "blue"),
    limits = c(1, 0),
    breaks = c(0, 0.05, 0.1, 0.25, 0.5, 1),
    trans = "reverse"
  )

```
```{r}
plot(Hierar_cl)
```

